version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: MelodyAdminPass
      POSTGRES_USER: MelodyAdmin
      POSTGRES_DB: MelodyDatabase
    ports:
      - 5432:5432
    volumes:
      - my_pgdata:/var/lib/postgresql/data
      

volumes:
  my_pgdata:
